In [1]:
import pandas as pd
import numpy as np

import seaborn as sns 
import matplotlib.pyplot as plt 

from pathlib import Path

import warnings
warnings.filterwarnings("ignore")

In [2]:
DATA = Path('data')
TRAIN_DATA = DATA / 'Train.csv'
TEST_DATA = DATA / 'Test.csv'

In [3]:
df = pd.read_csv(TRAIN_DATA)

In [4]:
df.head()

,sample_id,time,lat,lon,TWS_t,SPEI_01_t,SPEI_03_t,SPEI_06_t,SPEI_12_t,SOIL_MOISTURE_t,month_sin,month_cos,target
0,20020501_-55.5_-68.5,2002-05-01,-55.5,-68.5,0.876217,-1.584223,-1.701647,-2.015145,-1.912281,-1.827801,0.5,-0.866025,0.207665
1,20020501_-55.5_-67.5,2002-05-01,-55.5,-67.5,0.998124,-1.507424,-1.569591,-2.458965,-2.172938,-2.093158,0.5,-0.866025,0.634465
2,20020501_-54.5_-71.5,2002-05-01,-54.5,-71.5,0.813429,-1.473106,-1.151013,-0.524714,-0.908085,-0.932320,0.5,-0.866025,-0.337083
3,20020501_-54.5_-70.5,2002-05-01,-54.5,-70.5,0.841872,-1.460751,-1.487956,-0.588550,-0.936815,-0.928435,0.5,-0.866025,-0.148142
4,20020501_-54.5_-69.5,2002-05-01,-54.5,-69.5,0.872800,-1.275593,-1.729794,-0.243831,-0.870009,-1.053660,0.5,-0.866025,0.089539

In [5]:
len(df)

2154021

In [6]:
df['time'].unique()

<StringArray>
['2002-05-01', '2002-09-01', '2002-10-01', '2002-11-01', '2002-12-01',
 '2003-01-01', '2003-02-01', '2003-03-01', '2003-04-01', '2003-05-01',
 ...
 '2014-11-01', '2014-12-01', '2015-01-01', '2015-02-01', '2015-03-01',
 '2015-04-01', '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01']
Length: 138, dtype: str

In [9]:
df[(df['lat'] == -55.5) & (df['lon'] == -68.5)].head()

,sample_id,time,lat,lon,TWS_t,SPEI_01_t,SPEI_03_t,SPEI_06_t,SPEI_12_t,SOIL_MOISTURE_t,month_sin,month_cos,target
0,20020501_-55.5_-68.5,2002-05-01,-55.5,-68.5,0.876217,-1.584223,-1.701647,-2.015145,-1.912281,-1.827801,5.000000e-01,-8.660254e-01,0.207665
15551,20020901_-55.5_-68.5,2002-09-01,-55.5,-68.5,1.036390,-2.008365,0.473211,-1.612974,-1.825995,-0.600919,-1.000000e+00,-1.836970e-16,1.531529
31084,20021001_-55.5_-68.5,2002-10-01,-55.5,-68.5,1.531529,-1.997204,-1.138877,-1.284561,-1.896380,-1.549100,-8.660254e-01,5.000000e-01,1.741992
46694,20021101_-55.5_-68.5,2002-11-01,-55.5,-68.5,1.741992,-0.482901,-1.829547,-0.641067,-1.704742,-0.174987,-5.000000e-01,8.660254e-01,1.379470
62272,20021201_-55.5_-68.5,2002-12-01,-55.5,-68.5,1.379470,0.037373,-1.459194,-0.845474,-1.572221,-0.223959,-2.449294e-16,1.000000e+00,1.484929

In [23]:
tws_t_df = pd.crosstab(
    index=[df['lat'], df['lon']],
    columns=df['time'],
    values=df['TWS_t'],
    aggfunc='mean'
).reset_index()

tws_t_df.columns.name = None

In [24]:
tws_t_df.head()

,lat,lon,2002-05-01,2002-09-01,2002-10-01,2002-11-01,2002-12-01,2003-01-01,2003-02-01,2003-03-01,...,2014-11-01,2014-12-01,2015-01-01,2015-02-01,2015-03-01,2015-04-01,2015-05-01,2015-06-01,2015-07-01,2015-08-01
0,-55.5,-68.5,0.876217,1.036390,1.531529,1.741992,1.379470,1.484929,0.686617,2.296492,...,0.447144,0.170955,0.472663,0.681904,-0.243922,-1.017141,1.638603,1.575986,1.089499,0.516676
1,-55.5,-67.5,0.998124,1.045020,1.483422,1.774977,1.414530,1.462110,1.055810,2.386288,...,0.343059,0.084356,0.360642,0.405528,-0.217495,-0.664657,1.406535,1.385599,0.961369,0.474166
2,-54.5,-71.5,0.813429,1.362387,1.431042,1.632571,1.319646,1.742941,0.107697,1.749954,...,0.820838,0.497580,0.768374,1.140511,-0.132030,-1.100313,1.837369,1.646829,1.289551,0.453089
3,-54.5,-70.5,0.841872,1.271752,1.451170,1.599976,1.298777,1.669486,0.361988,1.885457,...,0.679653,0.418199,0.658309,0.780808,-0.278603,-0.853232,1.715993,1.526616,1.000966,0.312522
4,-54.5,-69.5,0.872800,1.204924,1.433888,1.578006,1.302289,1.625531,0.627274,1.984215,...,0.516131,0.299821,0.519130,0.503092,-0.350490,-0.582726,1.562339,1.394533,0.771009,0.199390